# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Milestone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Milestone
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Moya'

  target 'MilestoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MilestoneUITests' do
    # Pods for testing
  end

end
